name: CI

on: 
  push:
    branches: master
    paths-ignore: 
      - '**/**.md'
      - '.github/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn install --frozen-lockfile
        name: Install packages
      - run: yarn run build
        name: Build
      - run: yarn publish --no-git-tag-version --new-version "0.0.0-experimental-$(echo $GITHUB_SHA | cut -c1-9)" --tag experimental
        name: Publish experimental npm package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
